# Generated by Django 4.0.5 on 2022-06-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_title_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.CharField(default=1, max_length=300),
        ),
    ]
